<a href="https://colab.research.google.com/github/Manoj101295/Fake-news-NLP-project/blob/main/Bidirectional_LSTM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Fake news/train.csv")

In [ ]:
df=df.dropna()

In [ ]:
df.shape

(18285, 5)

In [ ]:
X=df.drop("label",axis=1)

In [ ]:
y=df.label

In [ ]:
import nltk

In [ ]:
import re
from nltk.stem import PorterStemmer

In [ ]:
le=PorterStemmer()

In [ ]:
text=X.copy()


In [ ]:
text.reset_index(inplace=True)

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
courpas=[]
for i in range(len(text)):
  review=re.sub('^[a-zA-Z]', ' ',text['title'][i])
  review=review.lower()
  review=review.split()
  review=[le.stem(word) for word in review if word not in stopwords.words('english')]
  review=' '.join(review)
  courpas.append(review)

In [ ]:
courpas

['ous dem aide: didn’t even see comey’ letter jason chaffetz tweet',
 'lynn: hillari clinton, big woman campu - breitbart',
 'hy truth might get fire',
 '15 civilian kill singl us airstrik identifi',
 'ranian woman jail fiction unpublish stori woman stone death adulteri',
 'acki mason: hollywood would love trump bomb north korea lack tran bathroom (exclus video) - breitbart',
 'enoît hamon win french socialist party’ presidenti nomin - new york time',
 'back-channel plan ukrain russia, courtesi trump associ - new york time',
 'bama’ organ action partner soros-link ‘indivisible’ disrupt trump’ agenda',
 'bc comedi sketch "real housew isis" caus outrag',
 'ussian research discov secret nazi militari base ‘treasur hunter’ arctic [photos]',
 'offici see link trump russia',
 'e: yes, paid govern troll social media, blogs, forum websit',
 'n major leagu soccer, argentin find home success - new york time',
 'ell fargo chief abruptli step - new york time',
 'nonym donor pay $2.5 million releas

In [ ]:
import tensorflow

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
voc_size=5000

In [ ]:
onehot=[one_hot(word,voc_size) for word in courpas]

In [ ]:
onehot

[[471, 3273, 2326, 3660, 1391, 2778, 995, 1175, 81, 3444, 660],
 [2112, 4650, 4990, 4605, 2259, 2772, 226],
 [712, 4602, 1432, 4138, 3677],
 [1911, 465, 2884, 2580, 1651, 1123, 269],
 [4250, 2259, 1617, 1809, 1474, 3625, 2259, 1913, 2865, 3498],
 [233,
  1111,
  3182,
  4393,
  4772,
  1228,
  2443,
  3363,
  3843,
  54,
  4854,
  2647,
  4415,
  4163,
  226],
 [674, 978, 2414, 1116, 1047, 1272, 2432, 1785, 847, 3072, 3292],
 [541, 1181, 3590, 2063, 4146, 2210, 1228, 839, 847, 3072, 3292],
 [826, 2504, 3978, 4850, 491, 2008, 774, 2840, 3806, 4814],
 [234, 418, 341, 667, 3916, 781, 158, 3427],
 [4441, 764, 4101, 3641, 3596, 4804, 2496, 3263, 4328, 1978, 2412],
 [3302, 2778, 2008, 1228, 4146],
 [355, 1460, 4001, 3312, 4174, 2420, 4653, 4970, 581, 2995],
 [1143, 3127, 4339, 2908, 3108, 1362, 959, 1638, 847, 3072, 3292],
 [1688, 431, 2839, 1578, 1472, 847, 3072, 3292],
 [378, 4458, 4950, 2031, 298, 3037, 2063, 2056, 2184, 220, 2398, 3231],
 [1598, 4275, 3257],
 [118, 1632, 1340, 4971, 1228

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
length=20
onehot_pad=pad_sequences(onehot,maxlen=length)

In [ ]:
print(onehot_pad)

[[   0    0    0 ...   81 3444  660]
 [   0    0    0 ... 2259 2772  226]
 [   0    0    0 ... 1432 4138 3677]
 ...
 [   0    0    0 ...  847 3072 3292]
 [   0    0    0 ...  514 4610  115]
 [   0    0    0 ... 2377 2295 1583]]


In [ ]:
len(onehot_pad)

18285

In [ ]:
X=np.array(onehot_pad)
y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=.75,random_state=100)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Bidirectional

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,64,input_length=length))
model.add(Bidirectional(LSTM(10)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 64)            320000    
_________________________________________________________________
bidirectional_4 (Bidirection (None, 20)                6000      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 21        
Total params: 326,021
Trainable params: 326,021
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
215/215 [==============================] - 5s 13ms/step - loss: 0.5165 - accuracy: 0.7202 - val_loss: 0.2041 - val_accuracy: 0.9158
Epoch 2/10
215/215 [==============================] - 2s 10ms/step - loss: 0.1311 - accuracy: 0.9555 - val_loss: 0.2123 - val_accuracy: 0.9154
Epoch 3/10
215/215 [==============================] - 2s 10ms/step - loss: 0.0745 - accuracy: 0.9786 - val_loss: 0.2428 - val_accuracy: 0.9123
Epoch 4/10
215/215 [==============================] - 2s 10ms/step - loss: 0.0579 - accuracy: 0.9849 - val_loss: 0.2973 - val_accuracy: 0.9007
Epoch 5/10
215/215 [==============================] - 2s 10ms/step - loss: 0.0406 - accuracy: 0.9891 - val_loss: 0.3156 - val_accuracy: 0.9075
Epoch 6/10
215/215 [==============================] - 2s 10ms/step - loss: 0.0269 - accuracy: 0.9932 - val_loss: 0.3533 - val_accuracy: 0.9079
Epoch 7/10
215/215 [==============================] - 2s 10ms/step - loss: 0.0193 - accuracy: 0.9964 - val_loss: 0.3954 - val_accuracy: 0.9086

In [ ]:
pred=model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score




In [ ]:
print(confusion_matrix(y_test,pred))

[[2397  207]
 [ 245 1723]]


In [ ]:
print(accuracy_score(y_test,pred))

0.9011373578302713
