<a href="https://colab.research.google.com/github/Manoj101295/Fake-news-NLP-project/blob/main/Fake_News_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Fake news/train.csv")

In [ ]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
df.shape

(20800, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [ ]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [ ]:
X=df.drop("label",axis=1)

In [ ]:
y=df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf


In [ ]:
tf.__version__

'2.4.1'

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=10000

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
messege=X.copy()

In [ ]:
messege.reset_index(inplace=True)

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
import re

In [ ]:
from nltk import corpus

In [ ]:
from nltk.corpus import stopwords

In [ ]:
messege.reset_index(inplace=True)

In [ ]:
ps=PorterStemmer()
corpes=[]
for i in range(0,len(messege)):
  review=re.sub('[^a-zA-Z]',' ', messege['title'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if word not in stopwords.words("english")]
  review=" ".join(review)
  corpes.append(review)




In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
one_words=[one_hot(words,voc_size) for words in corpes ]

In [ ]:
voc_size

10000

In [ ]:
one_words

[[5801, 5324, 4265, 615, 1202, 6121, 2355, 6737, 4737, 2131],
 [9328, 6643, 381, 1774, 6189, 7387, 7664],
 [9129, 2791, 7864, 3744],
 [8764, 9183, 574, 4416, 2988, 6245],
 [9099, 6189, 9452, 3415, 2462, 2587, 6189, 6606, 5418, 2254],
 [2710,
  2140,
  2623,
  5700,
  7917,
  7418,
  8247,
  2115,
  443,
  530,
  1873,
  7895,
  377,
  2862,
  7664],
 [381, 7052, 876, 2343, 4112, 7313, 5748, 5129, 5782, 9319, 213],
 [2016, 7855, 1899, 4005, 8973, 4605, 7418, 2819, 5782, 9319, 213],
 [8250, 2319, 6398, 8217, 1214, 1233, 7325, 878, 7418, 5559],
 [1856, 2428, 539, 2629, 7557, 1018, 9880, 3343],
 [8803, 5184, 6816, 3630, 5265, 2706, 8967, 7889, 137, 2276, 7410],
 [4416, 1845, 1202, 1233, 7418, 8973],
 [2555, 7580, 3433, 2664, 1753, 3852, 1855, 5431, 3893],
 [683, 451, 3842, 365, 1534, 9937, 6607, 5782, 9319, 213],
 [7055, 7110, 1168, 8670, 5545, 5782, 9319, 213],
 [5851, 5110, 1337, 2634, 3678, 2850, 6952, 4658, 3065, 963],
 [2411, 9063, 6643],
 [252, 1455, 1168, 4310, 7418, 3097, 4353, 766

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
words_padd=pad_sequences(one_words,maxlen=20,padding="pre")

In [ ]:
print(words_padd)

[[   0    0    0 ... 6737 4737 2131]
 [   0    0    0 ... 6189 7387 7664]
 [   0    0    0 ... 2791 7864 3744]
 ...
 [   0    0    0 ... 5782 9319  213]
 [   0    0    0 ... 2937 9404 9556]
 [   0    0    0 ... 3205 2644 6569]]


In [ ]:
words_padd[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 5801,
       5324, 4265,  615, 1202, 6121, 2355, 6737, 4737, 2131], dtype=int32)

In [ ]:
len(words_padd)

18285

In [ ]:
words_padd=np.array(words_padd)
y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(words_padd,y,train_size=0.75,random_state=100)

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,64,input_length=20))
model.add(Dense(1,activation='sigmoid'))
model.add(LSTM(100))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 20, 64)            640000    
_________________________________________________________________
dense_6 (Dense)              (None, 20, 1)             65        
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               40800     
Total params: 680,865
Trainable params: 680,865
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
215/215 [==============================] - 33s 13ms/step - loss: 2.8673 - accuracy: 0.0000e+00 - val_loss: 2.1630 - val_accuracy: 0.0000e+00
Epoch 2/10
215/215 [==============================] - 2s 11ms/step - loss: 2.0458 - accuracy: 4.1288e-06 - val_loss: 1.3030 - val_accuracy: 0.0000e+00
Epoch 3/10
215/215 [==============================] - 2s 11ms/step - loss: 1.2350 - accuracy: 3.4014e-04 - val_loss: 1.3768 - val_accuracy: 0.1019
Epoch 4/10
215/215 [==============================] - 2s 11ms/step - loss: 1.1019 - accuracy: 0.2506 - val_loss: 1.0145 - val_accuracy: 0.1975
Epoch 5/10
215/215 [==============================] - 2s 11ms/step - loss: 0.8563 - accuracy: 0.3351 - val_loss: 0.8698 - val_accuracy: 0.3747
Epoch 6/10
215/215 [==============================] - 2s 11ms/step - loss: 0.6956 - accuracy: 0.2839 - val_loss: 0.7978 - val_accuracy: 0.0886
Epoch 7/10
215/215 [==============================] - 2s 11ms/step - loss: 0.5990 - accuracy: 0.2136 - val_loss: 0.7746 -

In [ ]:
words_padd

array([[   0,    0,    0, ..., 6737, 4737, 2131],
       [   0,    0,    0, ..., 6189, 7387, 7664],
       [   0,    0,    0, ..., 2791, 7864, 3744],
       ...,
       [   0,    0,    0, ..., 5782, 9319,  213],
       [   0,    0,    0, ..., 2937, 9404, 9556],
       [   0,    0,    0, ..., 3205, 2644, 6569]], dtype=int32)

In [ ]:
y

array([1, 0, 1, ..., 0, 1, 1])

In [ ]:
from tensorflow.keras.layers import Dropout

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,64,input_length=20))
model.add(Dropout(0.3))

model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
pred=model.predict(X_test)

In [ ]:
sent_length=20
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
215/215 [==============================] - 4s 13ms/step - loss: 0.4394 - accuracy: 0.7718 - val_loss: 0.1866 - val_accuracy: 0.9189
Epoch 2/10
215/215 [==============================] - 3s 12ms/step - loss: 0.1356 - accuracy: 0.9491 - val_loss: 0.1933 - val_accuracy: 0.9195
Epoch 3/10
215/215 [==============================] - 3s 12ms/step - loss: 0.0780 - accuracy: 0.9731 - val_loss: 0.2272 - val_accuracy: 0.9230
Epoch 4/10
215/215 [==============================] - 3s 12ms/step - loss: 0.0593 - accuracy: 0.9802 - val_loss: 0.2420 - val_accuracy: 0.9250
Epoch 5/10
215/215 [==============================] - 2s 12ms/step - loss: 0.0367 - accuracy: 0.9874 - val_loss: 0.3491 - val_accuracy: 0.9245
Epoch 6/10
215/215 [==============================] - 2s 12ms/step - loss: 0.0238 - accuracy: 0.9918 - val_loss: 0.3353 - val_accuracy: 0.9245
Epoch 7/10
215/215 [==============================] - 3s 12ms/step - loss: 0.0176 - accuracy: 0.9943 - val_loss: 0.3820 - val_accuracy: 0.9151

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [ ]:
pred=model.predict_classes(X_test)


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
pred

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]], dtype=int32)

In [ ]:
len(pred)

4572

In [ ]:
print(confusion_matrix(y_test,pred))

[[2391  213]
 [ 159 1809]]


In [ ]:
print(accuracy_score(y_test,pred))

0.9186351706036745


In [ ]:
y_test

array([0, 1, 0, ..., 1, 1, 1])